# google analytics
#### included for production deploys
google_analytics_id = "G-BNBKE8JCEF" # example: UA-123456-78, for more info, read the article https://support.google.com/analytics/answer/1008080?hl=en